version: "3.9"
   
services:

  zookeeper:
    image: wurstmeister/zookeeper
    restart: "always"
    ports:
      - "2181:2181"
    networks: 
        kafkacluster:

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    restart: "always"
    ports:
        - "9092:9092"
    hostname: kafka.internal
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka.internal
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_CREATE_TOPICS: "quote-events-topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #   - ${KAFKA_DATA}/500:/kafka
    networks: 
       kafkacluster:
            aliases:
                - kafka.internal
    depends_on:
        - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop:3.27.0
    restart: "always"
    ports:
        - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    networks:
        kafkacluster:
    depends_on:
      - "kafka"
