name: Run App in Pipeline

on:
  push:
    branches: [ master , "dev" ]
  pull_request:
    branches: [ master , "dev" ]

jobs:

  RunApp:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build kafka
      run: docker-compose -f docker-compose-base.yml -f docker-compose-kafka.yml up -d --build zookeeper kafka kafka2 kafka3 kafdrop 
    - name: Run App
      run: docker-compose -f docker-compose-base.yml up --build financialapp
