name: Run App in Pipeline

on:
  push:
    branches: [ master , dev ]

jobs:

  RunApp:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build MySql cluster
      run: |
        export COMPOSE_PROJECT_NAME="fa"
        docker-compose -f docker-compose-base.yml -f docker-compose-mysql.yml up -d ndb_mgmd ndbd1 ndbd2 mysql
    - name: Build Kafka cluster
      run: |
        export COMPOSE_PROJECT_NAME="fa"
        docker-compose -f docker-compose-base.yml -f docker-compose-kafka.yml up -d zookeeper kafka kafka2 kafka3 kafdrop 
    - name: Run App
      run: |
        export COMPOSE_PROJECT_NAME="fa"
        docker-compose -f docker-compose-base.yml up --build financialapp
